name: flutter_getx_base
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  get_it: ^8.0.3
  dio: ^5.4.0
  injectable: ^2.1.0
  flex_color_picker: ^3.6.0
  flutter_svg: ^2.0.5
  equatable: ^2.0.5
  flutter_blurhash: ^0.9.1
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  flutter_native_splash: ^2.2.19
  image_picker: ^1.0.5
  image_cropper: ^9.1.0
  permission_handler: ^12.0.0+1
  google_fonts: ^6.2.1
  sqflite: ^2.2.7
  timezone: ^0.10.1
  json_annotation: ^4.9.0
  url_launcher: ^6.2.5
  timeago: ^3.6.1
  flutter_image_compress: ^2.3.0
  flutter_rounded_date_picker: ^3.0.4
  pull_to_refresh: ^2.0.0
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg_provider: ^1.0.7 
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  get_cli: ^1.9.1
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0


flutter_native_splash:
  color: '#FFFFFF'
  image: assets/icons/launcher/logo_no_bg.png
  android_screen_orientation: locked
  web: false

dev_dependencies: 
  flutter_lints: ^6.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.14.4
  flutter_gen_runner: ^5.1.0+1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher/logo.png"

flutter: 
  assets: 
    - assets/
    - assets/icons/
    - assets/images/
    - assets/icons/launcher/
  uses-material-design: true